config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  get '/home_brokers', to: 'pages#home_brokers', as: 'home_brokers'
  get '/home_agents', to: 'pages#home_agents', as: 'home_agents'
  
  get 'agents', to: 'agents#index'
  get 'agents/new', to: 'agents#new', as: 'new_agent'
  post 'agents/create', to: 'agents#create', as: 'create_agent'

  get 'agents/show/:user_id', to: 'agents#show', as: 'show_agent'
  post 'agents/edit/:user_id', to: 'agents#edit', as: 'edit_agent'

  get 'agents/assign_client/:user_id', to: 'agents#assign_client', as: 'assign_client'
  post 'agents/create_assignation/', to: 'agents#create_assignation', as: 'create_assignation'

  match '/search_brokers', to: 'pages#search_brokers', as: 'search_brokers', via: [:get, :post]
  
  get 'clients/refer_broker/:user_id', to: 'clients#refer_broker', as: 'refer_broker'
  
  get 'clients/refer_agent/:user_id', to: 'clients#refer_agent', as: 'refer_agent'
  
  get 'clients/assign_broker/:user_id', to: 'clients#assign_broker', as: 'assign_broker'
  post 'clients/change_broker/:user_id', to: 'clients#change_broker', as: 'change_broker'


  post 'clients/create_referral/', to: 'clients#create_referral', as: 'create_referral'

  get 'clients', to: 'clients#index'
  get 'clients/new', to: 'clients#new', as: 'new_client'
  post 'clients/create_client', to: 'clients#create_client', as: 'create_client'

  get 'clients/show/:user_id', to: 'clients#show', as: 'show_client'
  post 'clients/update_client/:user_id', to: 'clients#update_client', as: 'update_client'

  get 'clients/edit/:user_id', to: 'clients#edit', as: 'edit_client'
  get 'update_agent/:id', to: 'agents#update', as: 'update_agents'
  
  get 'profile/view_profile/:id', to: 'profile#view_profile', as: 'view_profile'
  match 'profile/update_profile', to: 'profile#update_profile', as: 'update_profile', via: [:get, :post]


  devise_for :users
  get 'brokers_locations', to: 'pages#get_brokers_locations', as: 'brokers_locations'
  root 'pages#home'

  post 'get_states_by_country/:country_id', to: 'pages#get_states_by_country'

  post 'get_cities_by_country_and_state/:country/:state_id', to: 'pages#get_cities_by_country_and_state'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  
  get 'dashboard/show_user/:user_id', to: 'dashboard#show_user', as: 'show_user'

  post 'dashboard/edit_user/:user_id', to: 'dashboard#edit_user', as: 'edit_user'

  get 'transactions', to: 'transactions#index', as: 'transactions'

  get 'remove_user/:user_id', to: 'dashboard#remove_user', as: 'remove_user'

  match "clients/refer_client_from_broker", to: "clients#refer_client_from_broker", as: 'refer_client_from_broker', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  before_action :has_valid_role

  def index
    # admin only can see brokers
    @users = User.all.where('id > ?', 0).reject{|u| u.role.downcase == 'admin'}
  end

  def show_user
    @user = User.find(params[:user_id])
  end

  def edit_user
    user_id = params[:user_id]
    user = User.find(user_id)
    user.first_name = params[:first_name] if params[:first_name]
    user.last_name = params[:last_name] if params[:last_name]
    user.phone = params[:phone] if params[:phone]
    user.email = params[:email] if params[:email]
    user.user_state = params[:user_state] if params[:user_state]
    
    if user.save!
      UserMailer.broker_actived_from_admin(user_id).deliver_now
      redirect_to dashboard_path(user_id), flash: {notice: "User successfully updated"}
    else
      render :edit
    end
  end

  def remove_user
    session[:user_id] = nil    
    byebug
    user = User.find(params[:user_id])
    user.destroy
    redirect_to dashboard_path, flash: {notice: "User successfully removed"}
  end
  

  private 

  def has_valid_role
    redirect_to root_path unless current_user.role.downcase == 'admin'
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="clients-container">  
  <h2>Usuarios</h2>
  <div class="list">
  <div class="actions d-grid col-10 justify-content-md-start">
    <%# link_to "New Client", new_client_path, class: "btn btn-primary btn-block mb-4" %>
  </div>
  <table class="table">
    <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">name</th>
          <th scope="col">email</th>
          <th scope="col">phone</th>   
          <th scope="col">User status</th>
          <th scope="col">Role</th>          
          <th scope="col"></th>
        </tr>
    </thead>
    <tbody>
    <% count = 0 %>
        <% if @users %>
          <% @users.each do |user| %>
            <tr>
              <td><%= count += 1 %></td>
              <td><%= user.full_name %></td>
              <td><%= user.email %></td>
              <td><%= user.phone %></td>
              <td><%= user.user_state%></td>
              <td><%= user.role %></td>
              <% if user.role.downcase == 'broker' %>
              <td><%= link_to "Edit", show_user_path(user.id), class: "btn btn-success" %></td>                            
              <% end %>
              
            </tr>
          <% end %> 
        <% end %>
    </tbody>
  </table>

app/views/dashboard/show_user.html.erb
<div class="container profile-form">

  <% if @user.errors.any? %>
      <div id="errorExplanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <%= form_with(url: edit_user_path(@user), local: true, method: "post") do |f| %>
    <h2>Edit User</h2>
    
    <div class="form-outline mb-4">
      <%= f.label :first_name, class: "form-label" %><br />
      <%= f.text_field :first_name, value: @user.first_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :last_name, class: "form-label" %><br />
      <%= f.text_field :last_name, value: @user.last_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :phone, class: "form-label" %><br />
      <%= f.number_field :phone, value: @user.phone, autofocus: true, autocomplete: "Phone", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :email, class: "form-label" %><br />
      <%= f.email_field :email, value: @user.email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>

    <br/>

    <div class="row g-3">
      <div class="col-md-2">
        <%= f.label "User state:", class: "form-label" %><br />
      </div>
      <div class="col-md-2">        
        <%= radio_button_tag :user_state, "Inactive", @user.user_state.downcase == 'inactive' %>
        <%= f.label "Inactive", class: "form-label" %><br />
      </div>
      
      <div class="col-md-4">
        <%= radio_button_tag :user_state, "Active", @user.user_state.downcase == 'active' %>
        <%= f.label "Active", class: "form-label" %><br />
      </div>
    </div>
    
    <br/>
    
    <div class="actions d-grid col-12 mx-auto">
      <%= f.submit "Update", class: "btn btn-success" %>      
    </div>

  <% end %>
</div>