config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  get '/home_brokers', to: 'pages#home_brokers', as: 'home_brokers'
  get '/home_agents', to: 'pages#home_agents', as: 'home_agents'
  
  get 'agents', to: 'agents#index'
  get 'agents/new', to: 'agents#new', as: 'new_agent'
  post 'agents/create', to: 'agents#create', as: 'create_agent'

  get 'agents/show/:user_id', to: 'agents#show', as: 'show_agent'
  post 'agents/edit/:user_id', to: 'agents#edit', as: 'edit_agent'

  get 'agents/assign_client/:user_id', to: 'agents#assign_client', as: 'assign_client'
  post 'agents/create_assignation/', to: 'agents#create_assignation', as: 'create_assignation'

  match '/search_brokers', to: 'pages#search_brokers', as: 'search_brokers', via: [:get, :post]
  
  get 'clients/refer_broker/:user_id', to: 'clients#refer_broker', as: 'refer_broker'
  
  get 'clients/refer_agent/:user_id', to: 'clients#refer_agent', as: 'refer_agent'
  
  get 'clients/assign_broker/:user_id', to: 'clients#assign_broker', as: 'assign_broker'
  post 'clients/change_broker/:user_id', to: 'clients#change_broker', as: 'change_broker'


  post 'clients/create_referral/', to: 'clients#create_referral', as: 'create_referral'

  get 'clients', to: 'clients#index'
  get 'clients/new', to: 'clients#new', as: 'new_client'
  post 'clients/create_client', to: 'clients#create_client', as: 'create_client'

  get 'clients/show/:user_id', to: 'clients#show', as: 'show_client'
  post 'clients/update_client/:user_id', to: 'clients#update_client', as: 'update_client'

  get 'clients/edit/:user_id', to: 'clients#edit', as: 'edit_client'
  get 'update_agent/:id', to: 'agents#update', as: 'update_agents'
  
  get 'profile/view_profile/:id', to: 'profile#view_profile', as: 'view_profile'
  match 'profile/update_profile', to: 'profile#update_profile', as: 'update_profile', via: [:get, :post]


  devise_for :users
  get 'brokers_locations', to: 'pages#get_brokers_locations', as: 'brokers_locations'
  root 'pages#home'

  post 'get_states_by_country/:country_id', to: 'pages#get_states_by_country'

  post 'get_cities_by_country_and_state/:country/:state_id', to: 'pages#get_cities_by_country_and_state'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  
  get 'dashboard/show_user/:user_id', to: 'dashboard#show_user', as: 'show_user'

  post 'dashboard/edit_user/:user_id', to: 'dashboard#edit_user', as: 'edit_user'

  get 'transactions', to: 'transactions#index', as: 'transactions'

  get 'remove_user/:user_id', to: 'dashboard#remove_user', as: 'remove_user'

  match "clients/refer_client_from_broker", to: "clients#refer_client_from_broker", as: 'refer_client_from_broker', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_agent_profile.html.erb
<div class="col-sm-6">  
  <div class="form-outline">
    <%= form.label :country, class: "form-label" %><br />
    <%= form.select(:country, @countries, {prompt: "select country", selected:  @current_country }, {:class => 'form-control' }) %>  
  </div>

  <div class="form-outline">
    <%= form.label :state, class: "form-label" %><br />
    <%= form.select(:state, [], {prompt: "select state", selected: @current_state }, { :class => 'form-control' }) %>    
  </div>

  <div class="form-outline">
    <%= form.label :city, class: "form-label" %><br />
    <%= form.select(:city, [], {prompt: "select city", selected: @current_city }, { :class => 'form-control' } ) %>
  </div>

  <div class="form-outline">
    <%= form.label :address, class: "form-label" %><br />
    <%= form.text_field :address, value: @agent.address, autofocus: true, autocomplete: "Address", class: "form-control" %>  
  </div>

  <div class="form-outline">
    <%= form.label "Company zip code", class: "form-label" %><br />
    <%= form.text_field :zip_code, value: @agent.zip_code, autofocus: true, autocomplete: "zip_code", class: "form-control" %>  
  </div>

  <div class="form-outline" style="display:none;">
    <%= form.label "Registerd in", class: "form-label" %><br />
    <%= form.text_field :created_at, value: current_user.created_at.strftime("%Y-%m-%d"), readonly: true, class: "form-control" %>    
  </div>
</div>

app/views/partials/_broker_profile.html.erb
<div class="col-sm-4">
  <div class="form-outline mb-4">
    <%= form.label :company_name, class: "form-label" %><b> *</b><br />
    <%= form.text_field :company_name, value: @broker.company_name, autofocus: true, autocomplete: "company_name", class: "form-control" %>  
  </div>

  <div class="form-outline mb-4">
    <%= form.label :company_licence, class: "form-label" %><br />
    <%= form.text_field :company_licence, value: @broker.company_licence, autofocus: true, autocomplete: "company_licence", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :years_in_bussiness, class: "form-label" %><br />
    <%= form.text_field :years_in_bussiness, value: @broker.years_in_bussiness,  autofocus: true, autocomplete: "years_in_bussiness", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :insurance_carrier, class: "form-label" %><br />
    <%= form.text_field :insurance_carrier, value: @broker.insurance_carrier, autofocus: true, autocomplete: "insurance_carrier", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :insurance_policy, class: "form-label" %><br />
    <%= form.text_field :insurance_policy, value: @broker.insurance_policy, autofocus: true, autocomplete: "insurance_policy", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :broker_licence, class: "form-label" %><br />
    <%= form.text_field :licence, value: @broker.licence, autofocus: true, autocomplete: "licence", class: "form-control" %>  
  </div>
</div>

<div class="col-sm-4">
  <div class="form-outline mb-4">
    <%= form.label :broker_licencia_expiration_date, class: "form-label" %><br />
    <%= form.date_field :licencia_expiration_date, value: @broker.licencia_expiration_date, autofocus: true, autocomplete: "licencia_expiration_date", class: "form-control" %>    
  </div>

  <div class="form-outline mb-4">  
    <%= form.hidden_field :created_at, value: current_user.created_at.strftime("%Y-%m-%d"), readonly: true, class: "form-control" %>    
  </div>

  <div class="form-outline mb-4">  
    <%= form.label :company_country, class: "form-label" %><b> *</b><br />
    <%= form.select(:country, @countries, {prompt: "select country", selected: @current_country }, {:class => 'form-control' }) %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :company_state, class: "form-label" %><b> *</b><br />
    <%= form.select(:state, @states, {prompt: "select state", selected: @current_state }, { :class => 'form-control' }) %>
  </div>

  <div class="form-outline mb-4">
    <%= form.label :company_city, class: "form-label" %><b> *</b><br />
    <%= form.select(:city, @cities, {prompt: "select city", selected: @current_city }, { :class => 'form-control' } ) %>
  </div>

  <div class="form-outline mb-4">  
    <%= form.label :company_address, class: "form-label" %> <b> *</b><br />
    <%= form.text_field :address, value: @broker.address, autofocus: true, autocomplete: "Address", class: "form-control" %>    
  </div>

  <div class="form-outline mb-4">
    <%= form.label "Company zip code", class: "form-label" %><br />
    <%= form.text_field :reserver_zip_code, maxlength: 5, size: 5, value: @broker.reserver_zip_code, autofocus: true, autocomplete: "reserver_zip_code", class: "form-control" %>    
  </div>
</div>

app/views/partials/_footer.html.erb
<footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>About</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>
          </div>

          <div class="col-lg-2 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

         

          <div class="col-lg-4 col-md-6 footer-newsletter">
            <h4>Join Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
            <form action="" method="post">
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>

        </div>
      </div>
    </div>

    <%# <div class="container d-md-flex py-4">

      <div class="me-md-auto text-center text-md-start">
        <div class="copyright">
          &copy; Copyright <strong><span>Lumia</span></strong>. All Rights Reserved
        </div>
        <div class="credits">
          <!-- All the links in the footer should remain intact. -->
          <!-- You can delete the links only if you purchased the pro version. -->
          <!-- Licensing information: https://bootstrapmade.com/license/ -->
          <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/lumia-bootstrap-business-template/ -->
          Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
        </div>
      </div>
      <div class="social-links text-center text-md-right pt-3 pt-md-0">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
    </div> %>
</footer>
<script
      src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_KEY'] %>"
      defer
></script>

app/views/partials/_header.html.erb
    

<header id="header" class="fixed-top d-flex align-items-center">
  <div class="container d-flex align-items-center">
        <div class="logo me-auto">
          <h1><a href="/">Brokers</a>
          </h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>
        <nav id="navbar" class="navbar order-last order-lg-0">
          <ul>
            <% if user_signed_in? %>
              <% if current_user.role.downcase == "broker" %>
              <li> <%= link_to 'Home', home_brokers_path %> </li>                
              <% else %>
                <li> <%= link_to 'Home', home_agents_path %> </li>
              <% end %>
            <% else %>
              <li><a class="nav-link scrollto active" href="/">Home</a></li>
            <% end %>
            
            <% if user_signed_in? && current_user.role.downcase == 'admin' %>
            <li> <%= link_to 'Usuarios', dashboard_path %> </li>
            <li> <%= link_to 'Transactions', transactions_path %> </li>
            <% end %>
            <% if user_signed_in? %>
              <% if current_user.role.downcase != "admin" %>
              <li> <%= link_to 'Clients', clients_path %> </li>
              <% end %>
              <% if current_user.role.downcase == "broker" %>
              <li> <%= link_to 'Agents', agents_path %> </li>
              <li> <%= link_to 'Brokers', search_brokers_path %> </li>
              <% elsif current_user.role.downcase == "agent" %>
              <li> <%= link_to 'Brokers', search_brokers_path %> </li>
              <% end %>
              
              <li class="dropdown"><a href="#"><span>Profile</span> <i class="bi bi-chevron-down"></i></a>
                <ul>
                  <% if current_user.role.downcase != "admin" %>
                    <li><%= link_to "My profile", profile_index_path, :method => :get %>
                  <% end %>
                  <li><%= link_to "Edit password", edit_user_registration_path, :method => :get %>                
                  
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>                
                </ul>
              </li>
            <% end %>
            <% if !user_signed_in? %>
              <li><%= link_to "Login", new_user_session_path, :method => :get, class:"nav-link scrollto" %></li>
              <li><%= link_to "Register", new_user_registration_path, :method => :get, class: "nav-link scrollto" %></li>              
            <% end %>
          </ul>
          <i class="fa-solid fa-bars mobile-nav-toggle"></i>
          
        </nav><!-- .navbar -->

        <div class="header-social-links d-flex align-items-center">
          <a href="#" class="twitter"><i class="fa-brands fa-twitter"></i></a>
          <a href="#" class="facebook"><i class="fa-brands fa-facebook"></i></a>
          <a href="#" class="instagram"><i class="fa-brands fa-instagram"></i></a>
          <a href="#" class="linkedin"><i class="fa-brands fa-linkedin"></i></a>
        </div>
  </div>  
</header>