config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  get '/home_brokers', to: 'pages#home_brokers', as: 'home_brokers'
  get '/home_agents', to: 'pages#home_agents', as: 'home_agents'
  
  get 'agents', to: 'agents#index'
  get 'agents/new', to: 'agents#new', as: 'new_agent'
  post 'agents/create', to: 'agents#create', as: 'create_agent'

  get 'agents/show/:user_id', to: 'agents#show', as: 'show_agent'
  post 'agents/edit/:user_id', to: 'agents#edit', as: 'edit_agent'

  get 'agents/assign_client/:user_id', to: 'agents#assign_client', as: 'assign_client'
  post 'agents/create_assignation/', to: 'agents#create_assignation', as: 'create_assignation'

  match '/search_brokers', to: 'pages#search_brokers', as: 'search_brokers', via: [:get, :post]
  
  get 'clients/refer_broker/:user_id', to: 'clients#refer_broker', as: 'refer_broker'
  
  get 'clients/refer_agent/:user_id', to: 'clients#refer_agent', as: 'refer_agent'
  
  get 'clients/assign_broker/:user_id', to: 'clients#assign_broker', as: 'assign_broker'
  post 'clients/change_broker/:user_id', to: 'clients#change_broker', as: 'change_broker'


  post 'clients/create_referral/', to: 'clients#create_referral', as: 'create_referral'

  get 'clients', to: 'clients#index'
  get 'clients/new', to: 'clients#new', as: 'new_client'
  post 'clients/create_client', to: 'clients#create_client', as: 'create_client'

  get 'clients/show/:user_id', to: 'clients#show', as: 'show_client'
  post 'clients/update_client/:user_id', to: 'clients#update_client', as: 'update_client'

  get 'clients/edit/:user_id', to: 'clients#edit', as: 'edit_client'
  get 'update_agent/:id', to: 'agents#update', as: 'update_agents'
  
  get 'profile/view_profile/:id', to: 'profile#view_profile', as: 'view_profile'
  match 'profile/update_profile', to: 'profile#update_profile', as: 'update_profile', via: [:get, :post]


  devise_for :users
  get 'brokers_locations', to: 'pages#get_brokers_locations', as: 'brokers_locations'
  root 'pages#home'

  post 'get_states_by_country/:country_id', to: 'pages#get_states_by_country'

  post 'get_cities_by_country_and_state/:country/:state_id', to: 'pages#get_cities_by_country_and_state'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  
  get 'dashboard/show_user/:user_id', to: 'dashboard#show_user', as: 'show_user'

  post 'dashboard/edit_user/:user_id', to: 'dashboard#edit_user', as: 'edit_user'

  get 'transactions', to: 'transactions#index', as: 'transactions'

  get 'remove_user/:user_id', to: 'dashboard#remove_user', as: 'remove_user'

  match "clients/refer_client_from_broker", to: "clients#refer_client_from_broker", as: 'refer_client_from_broker', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  belongs_to :agent
  belongs_to :broker
  has_many :transactions

  def full_name
    "#{self.user.first_name} #{self.user.last_name}"
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_role_user
  before_action :validate_email_registered, only: [:create]
  before_action :has_valid_profile

  # Section list clients for brokers and agents
  def index
    #@clients = Client.all
    @title = current_user.role.downcase == "broker" ? "Broker Clients" : "Agents Clients"
    @clients, @inbound_referidos, @outbound_referidos = get_clients_by(@role_user)    
  end

  def new
    @user = User.new
    @client = Client.new
    select_referreds_by(@role_user)
  end

  def show
    @user_states = ApplicationHelper::USER_STATES
    @user = User.find(params[:user_id])
    client_id = @user.client.id
    @client = Client.find(client_id)
    @transaction = Transaction.find_by_client_id(client_id)
    @pdf_attached = @transaction.proof_check if @transaction
  end

  def edit
    @user_states = ApplicationHelper::USER_STATES
    @user = User.find(params[:user_id])
    client_id = @user.client.id
    @client = Client.find(client_id)
    @transaction = Transaction.find_by_client_id(client_id)
    @pdf_attached = @transaction.proof_check if @transaction
  end

  def update_client
    user_id = params[:user_id]
    user = User.find(user_id)
    transaction = Transaction.find_by_client_id(params[:client_id])    
    transaction.proof_check.attach(params[:proof_check]) if params[:proof_check]
    transaction.contract_price = params[:full_sale]
    transaction.close_date = DateTime.now.to_time
    transaction.commission = params[:commission]
    user.user_state =  params[:user_state]
    
    if user.update!(permit_params_user) && transaction.save
      UserMailer.client_updated_status(current_user, params[:client_id]).deliver_now
      redirect_to show_client_path(user_id), flash: {notice: "Client successfully updated"}
    else
      render :edit
    end
  end

  def create_client
    select_referreds_by(@role_user)
    @user = User.new(permit_params_user)
    if @user.save
      client = Client.new
      client.user_id = @user.id
      if current_user.role.downcase == 'broker'
        client.agent_id = 0
        client.broker_id = current_user.broker.id
      else        
        client.agent_id = current_user.agent.id
        client.broker_id = 0
      end
      client.save!

      flash[:success] = "Client was successfully created."
      redirect_to clients_path
    else
      render :new
    end
  end

  def refer_broker
    select_referreds_by(@role_user)
    @user = User.find(params[:user_id])
    @brokers = Broker.all
    @client = Client.find_by_user_id(@user.id)
    common_refer_attributes(@client)
  end

  def refer_agent
    select_referreds_by(@role_user)
    @user = User.find(params[:user_id])
    @client = Client.find_by_user_id(@user.id)
    @brokers = Broker.all
    common_refer_attributes(@client)
  end

  def refer_client_from_broker
    @brokers = Broker.all
    default_values_for_create_referreds
    @price_range_group_a =  [
      [0, 100000],
      [100000, 200000],
      [200000, 300000],
      [300000, 400000],
      [400000, 500000],
      [500000, 600000],
      [600000, 700000],
      [700000, 800000],
      [800000, 900000],
      [900000, 1000000]                    
    ]

    @price_range_group_b = price_range_group_b
    @client = params.include?(:email) ? create_client_from_broker : nil        

    unless @client.nil?
      @user = User.find(@client.user_id)
      @user.notes = params[:notes]
      @client.broker_id = params[:client][:broker_id].to_i
      @client.type_of_property = params[:type_of_property] if  params[:type_of_property]
      @client.number_of_rooms = params[:number_of_rooms] if params[:number_of_rooms]
      @client.number_of_bathrooms = params[:number_of_bathrooms] if params[:number_of_bathrooms]
      @client.parkng_lot = params[:parkng_lot] if params[:parkng_lot]
      @client.budget = params[:budget] if params[:budget]
  
      if @client.save && @user.save
        create_transaction_from_broker(params, @client)
        flash[:success] = "Refered created succesfully"
        redirect_to clients_path
      else
        render :refer_client_from_broker
      end
    end
  end

  def create_client_from_broker
    user = User.new(permit_params_user)
    user.with_lock do
      if user.save
        client = Client.new
        client.user_id = user.id
        client.agent_id = 0
        client.broker_id = current_user.broker.id
        client.save!
        client
      end
      #todo add validation to render with message errros
    end
  end

  def create_transaction_from_broker(params, client)
    origin_broker = current_user.broker.id
    @referral = Broker.find(origin_broker)
    destination_broker = params[:client][:broker_id]
    
    transaction_params = {
      origin_broker: origin_broker,
      destination_broker: destination_broker,
      client_id: client.id,
      property_address: params[:property_address],
    }
    
    current_transaction = Transaction.find_by_client_id(client.id)
    
    if current_transaction
      current_transaction.origin_broker = origin_broker
      current_transaction.destination_broker = destination_broker
      current_transaction.property_address = params[:property_address]
      current_transaction.save!
    else
      transaction = Transaction.create(transaction_params)
    end

    self.send_confirm_referred_email(origin_broker, destination_broker, client.id)
  end

  def create_referral #for refer agents and brokers
    client = Client.find(params[:client_id])
    user = User.find(client.user_id)
    user.notes = params[:notes]
    # for the agent_id, if the role is broker would take the agent selected in the form, otherwise would be the current agent
    # agent_id = current_user.role.downcase == 'broker' ? params[:client][:agent_id].to_i : current_user.agent.id
    # client.agent_id = agent_id
    
    # if role user is agent, the broker_id would be the agent's broker
    broker_id = current_user.role.downcase == 'agent' ? params[:client][:broker_id].to_i : current_user.broker.id
    client.broker_id = broker_id
    
    client.type_of_property = params[:type_of_property] if  params[:type_of_property]
    client.number_of_rooms = params[:number_of_rooms] if params[:number_of_rooms]
    client.number_of_bathrooms = params[:number_of_bathrooms] if params[:number_of_bathrooms]
    client.parkng_lot = params[:parkng_lot] if params[:parkng_lot]
    client.budget = params[:budget] if params[:budget]

    if client.save! && user.save!
      create_transaction(params, client)
      flash[:success] = "Refered created succesfully"
      redirect_to clients_path
    else
      render :refer_agent
    end
  end

  def create_transaction(params, client)
    if current_user.role.downcase == 'agent'      
      origin_agent = current_user.agent.id
      @referral = Agent.find(origin_agent)
      destination_broker = params[:client][:broker_id].to_i
      origin_broker = Agent.find(origin_agent).broker_id # clean origin broker, for refereds to external broker from agent
    end

    if current_user.role.downcase == 'broker'
      origin_broker = current_user.broker.id
      @referral = Broker.find(origin_broker)
      assigned_agent = params[:client][:agent_id].to_i
      client = Client.find(client.id)
      client.agent_id = assigned_agent
      client.save!
      destination_broker = assigned_agent.to_i > 0 ? 0 : current_user.broker.id
    end

    transaction_params = {
      origin_broker: origin_broker,
      destination_broker: destination_broker,
      origin_agent: origin_agent,
      assigned_agent: assigned_agent,
      client_id: client.id,                        
      property_address: params[:property_address],
    }
    
    current_transaction = Transaction.find_by_client_id(client.id)
    
    if current_transaction
      current_transaction.origin_broker = origin_broker
      current_transaction.destination_broker = destination_broker
      current_transaction.origin_agent = origin_agent || 0
      current_transaction.assigned_agent = assigned_agent
      current_transaction.property_address = params[:property_address]
      current_transaction.save!
    else
      transaction = Transaction.create(transaction_params)
    end

    self.send_confirm_referred_email(origin_agent || origin_broker, destination_broker, client.id)
  end

  def assign_broker
    @user = User.find(params[:user_id])
    @client = Client.find_by_user_id(@user.id)
    @brokers = Broker.all
  end

  def change_broker
    client = Client.find(params[:client_id])
    client.broker_id = params[:client][:broker_id]
    transaction = Transaction.find_by_client_id(params[:client_id])
    transaction.origin_broker = current_user.broker.id
    transaction.destination_broker = params[:client][:broker_id]
    if transaction.save! && client.save!
      flash[:success] = "Refered created succesfully"
      redirect_to clients_path
    else
      render :assign_broker
    end
  end

  private

  def common_refer_attributes(client)
    default_values_for_create_referreds

    unless client
      @current_type_of_property = client&.type_of_property
      @current_number_of_rooms = client&.number_of_rooms
      @current_parking_lot = client&.parkng_lot
      @current_number_of_bathrooms = client&.number_of_bathrooms  
    end    
  end

  def default_values_for_create_referreds
    @properties = ApplicationHelper::PROPERTIES
    @number_of_rooms = ApplicationHelper::ROOMS
    @parking_lots = ApplicationHelper::PARKING_LOTS
    @bathrooms = ApplicationHelper::BATHROOMS
  end

  def get_role_user
    @role_user = current_user.role
  end

  def validate_email_registered
    unless params[:email].empty?
      user = User.find_by_email(params[:email])
      if user
        flash[:error] = "Error creating User, email is already registered"
        redirect_to new_client_path
      end      
    end
  end

  def get_clients_by(role_user)    

app/views/clients/assign_broker.html.erb
<div class="container refer-client">
  <%= form_with(url: change_broker_path(@user), method: "post") do |f| %>
  <h2>Update client</h2>

  <%= f.hidden_field :client_id, value: @client.id %>

  <div class="form-outline mb-4">
    <%= f.label :first_name, class: "form-label" %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "First name", value: @client.user.first_name, readonly: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :last_name, class: "form-label" %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "Last name", value: @client.user.last_name, readonly: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :phone, class: "form-label" %><br />
    <%= f.text_field :phone, autofocus: true, autocomplete: "Phone", value: @client.user.email, readonly: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :email, class: "form-label" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: @client.user.email, readonly: true, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= f.label "Assign Broker", class: "form-label" %>
    <%= collection_select(:client, :broker_id, @brokers, :id, :full_name, {}, class: "form-control") %>
  </div>
  <br/>

  <br/>
  
  <div class="actions d-grid col-12 mx-auto">
    <%= f.submit "Refer", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/clients/edit.html.erb
<div class="container update-client">
  <% if @user.errors.any? %>
      <div id="errorExplanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>
  <div class="row">
    <%= form_with(url: update_client_path(@user), local: true, method: "post") do |f| %>
    <div class="col-md-12">
      <h2>Client Detail</h2>
      <%= f.hidden_field :client_id, value: @client.id %>
      <div class="form-outline mb-4">
        <%= f.label :first_name, class: "form-label" %><br />
        <%= f.text_field :first_name, value: @user.first_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
      </div>

      <div class="form-outline mb-4">
        <%= f.label :last_name, class: "form-label" %><br />
        <%= f.text_field :last_name, value: @user.last_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
      </div>

      <div class="form-outline mb-4">
        <%= f.label :phone, class: "form-label" %><br />
        <%= f.number_field :phone, value: @user.phone, autofocus: true, autocomplete: "Phone", class: "form-control" %>
      </div>

      <div class="form-outline mb-4">
        <%= f.label :email, class: "form-label" %><br />
        <%= f.email_field :email, value: @user.email, autofocus: true, autocomplete: "email", class: "form-control" %>
      </div>      
      
      <% unless @transaction.nil? %>
        <% if @transaction.origin_broker || @client.broker_id %>
          <%= f.label 'From Broker', class: "form-label" %><br />
          <%= f.text_field '', value: @transaction.origin_broker ? Broker.find(@transaction.origin_broker).user.full_name : Broker.find(@client.broker_id).user.full_name, readonly: true, class: "form-control" %>
        <% end %><br/>
      
        <% if  @transaction.assigned_agent %>
          <%= f.label 'Assigned Agent', class: "form-label" %><br />
          <%= f.text_field '', value: Agent.find(@transaction.assigned_agent).user.full_name, readonly: true, class: "form-control" %>      
        <% end %>
      <% end %>
    </div>      
    <br/>
          
    <div class="row">
      <div class="col-md-12">
        <%= f.label "User state:", class: "form-label" %><br />
      </div>
      <% @user_states.each do |state| %>
        <div class="col-md-6">
          <%= f.radio_button :user_state, state, checked: (@user.user_state == state) %>
          <%= f.label state, class: "form-label" %><br />
        </div>
      <% end %>    
      <br/><br/>
      <hr class="border-2 border-top ">
      <!-- Enable when close state is selected -->
      <div class="close-transaction-fields">
          <div class="form-outline mb-4">
            <%= f.label :proof_check_pdf, class: "form-label" %><br />         
              <%= link_to "proof check pdf", @pdf_attached if @pdf_attached.attached? %>
              <%= f.file_field(:proof_check, accept: 'pdf') %>
          </div>
          
          <div class="form-outline mb-4">
            <%= f.label 'commission %', class: "form-label" %><br />
            <%= f.text_field :commission, value: @user.commission, autofocus: true, class: "form-control" %>
          </div>

          <div class="form-outline mb-4">
            <%= f.label :full_sale, class: "form-label" %><br />
            <%= f.text_field :full_sale, value: @user.full_sale, autofocus: true, class: "form-control" %>
          </div>
        </div> 
        <div class="actions d-grid col-12 mx-auto">
          <%= f.submit "Update", class: "btn btn-success" %>
        </div>    
      </div>  
    <% end %>
  </div>
</div>

app/views/clients/index.html.erb
<div class="clients-container">  
  <h2><%= @title  %></h2>
  <div class="list">
  <div class="actions d-grid col-10 justify-content-md-start">
    <% if current_user.role.downcase == 'broker' %>
    <%= link_to "Refer Client", refer_client_from_broker_path, class: "btn btn-primary btn-block mb-4" %>
    <% else %>
    <%= link_to "New Client", new_client_path, class: "btn btn-primary btn-block mb-4" %>
    <% end %>
  </div>
  <% if  current_user.role.downcase == "agent" %>
    <h3>Unassign Clients</h3>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">name</th>
          <th scope="col">From Agent</th>
          <th scope="col">User status</th>
          <th scope="col"></th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
      <% count = 0 %>
      <% if @clients %>
        <% @clients.each do |client| %>
          <tr>
            <td><%= count += 1 %></td>
            <td><%= link_to client.full_name, show_client_path(client.user.id) %></td>
            <td><%= Agent.find(client.agent_id).full_name %></td> <!--update for from agent-->
            <td><%= client.user.role.downcase != 'broker' ? 'active' : 'inactive' %></td>          
            <% if current_user.role.downcase == 'agent' %>
              <td><%= link_to "Refer Broker", refer_broker_path(client.user.id), class: "btn btn-success" %></td>            
            <% else %>
              <td><%= link_to "Assign Agent", refer_agent_path(client.user.id), class: "btn btn-success" %></td>
              <td><%= link_to 'View Details', show_client_path(client.user.id), class: "btn btn-success" %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  <% end %>
  <br/>
  <h3>Inbound Clients</h3>
   <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">name</th>
        <% if current_user.role.downcase == 'broker'%>          
          <th scope="col">From</th>  
          <th scope="col">Assigned to</th>                   
        <% elsif current_user.role.downcase == 'agent' %> 
          <th scope="col">Origin broker</th>                  
          <th scope="col">Assigned agent</th>          
        <% end %>
        <th scope="col">User status</th>
          <th scope="col"></th>
          <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
     
    <% count = 0 %>
    <% if @inbound_referidos %>
      <% @inbound_referidos.each do |referido| %>
        <% unless referido.id == 0 %>
        <tr>
          <td><%= count += 1 %></td>
          <td><%= link_to referido.full_name, show_client_path(referido.user.id) %></td>                              
          <% if current_user.role.downcase == 'broker'%>
            <% 
            transaction = Transaction.where(client_id: referido.id)
            company_broker = Broker.find(transaction.last.origin_broker).company_name unless transaction
            from_user = (company_broker && company_broker.downcase == 'unassigned') ? Agent.find(Transaction.where(client_id: referido.id).last.origin_agent).user.full_name : current_user.broker.company_name
            assigned_to_broker = referido.broker.company_name
            assigend_to_agent = referido.agent.user.first_name

            assigned_to = 'unassigned'
            if assigned_to_broker.downcase != 'unassigned'
              assigned_to = assigned_to_broker
            end

            if assigend_to_agent && assigend_to_agent != 'unassigned'
              assigned_to = assigend_to_agent          
            end            
            %>
            <td><%= from_user %></td>
            <td><%= assigned_to %></td>
          <% elsif current_user.role.downcase == 'agent' %>
            <td><%= Broker.find(Transaction.where(client_id: referido.id).last.destination_broker).user.full_name %></td>
            <td><%= Agent.find(Transaction.where(client_id: referido.id).last.assigned_agent).user.full_name %></td>
          <% end %>        
          <td><%= referido.user.user_state %></td>
          <% if current_user.role.downcase == 'agent' %>
            <td><%= link_to "Manage", edit_client_path(referido.user.id), class: "btn btn-success" %></td>
          <% else %>
            <td><%= link_to "Refer Agent", refer_agent_path(referido.user.id), class: "btn btn-success" %></td>
            <td><%= link_to "Manage", edit_client_path(referido.user.id), class: "btn btn-success" %></td>
          <% end %>
        </tr>
        <% end %>
      <% end %>
    <% end %>
    </tbody>
  </table>

   <br/>
  <h3>Outbound Clients</h3>
   <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">name</th>
        <th scope="col">From</th>
        <th scope="col">Assigned Broker</th>
        <th scope="col">User status</th>
        <th scope="col"></th>               
      </tr>
    </thead>
    <tbody>    
     
    <% count = 0 %>
    <% if @outbound_referidos %>
      <% @outbound_referidos.each do |referido| %>
        <% unless referido.id == 0 %>
        <tr>
          <td><%= count += 1 %></td>
          <td><%= referido.full_name %></td>          
          <td><%= referido.agent.full_name %></td>          
          <td><%= Broker.find(Transaction.find_by_client_id(referido.id).destination_broker).company_name %></td>
          <td><%= referido.user.user_state %></td>
          <td><%= link_to 'View Details', show_client_path(referido.user.id), class: "btn btn-success" %></td>
        </tr>
        <% end %>
      <% end %>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container new-client">

  <% if @user.errors.any? %>
      <div id="errorExplanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <%= form_with(url: create_client_path(@user), local: true, method: "post") do |f| %>
  <h2>Create new Client</h2>
  <%= f.hidden_field :user_state, value: current_user&.role&.downcase == 'agent'  ? 'active' : 'inactive' %>
  <div class="form-outline mb-4">
    <%= f.label :first_name, class: "form-label" %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "First name", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :last_name, class: "form-label" %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :phone, class: "form-label" %><br />
    <%= f.number_field :phone, autofocus: true, autocomplete: "Phone", class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :email, class: "form-label" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
  </div>
  
  <% if current_user.role.downcase == 'agent' %>
  <div class="field" style="display:none;">
    <%= f.label "Assign Agent", class: "form-label" %>
    <%= collection_select(:client, :agent_id, @referreds, :id, :full_name, {}, class: "form-control") %>
  </div>
  <% end %>
  <br/>

  <%= f.hidden_field :role, value: "client", class: "form-control" %>
  

  <div class="field">
    <%= f.label "password (6 characters minimum)", class: "form-label" %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation, class: "form-label" %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
  </div>
  
  <div class="actions d-grid col-12 mx-auto">
    <%= f.submit "Create", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/clients/refer_client_from_broker.html.erb
<div class="container">


  <% if @client && @client.errors.any? %>
      <div id="errorExplanation">
        <% @client.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

 <% if @user && @user.errors.any? %>
      <div id="errorExplanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>
  
  <%= form_with(url: refer_client_from_broker_path(@user), method: "post") do |f| %>
    <h2>Refer Broker</h2>
    <div class="row justify-content-md-center">
      <%= render 'partials/broker/create_client', f: f %>    
      <%= render 'partials/broker/refer_client', f: f %>    
    </div>
    <div class="actions d-grid col-12 mx-auto">
      <%= f.submit "Refer", class: "btn btn-success" %>
    </div>
  <% end %>
</div>