config/routes.rb
Rails.application.routes.draw do
  get 'profile/index'

  get '/home_brokers', to: 'pages#home_brokers', as: 'home_brokers'
  get '/home_agents', to: 'pages#home_agents', as: 'home_agents'
  
  get 'agents', to: 'agents#index'
  get 'agents/new', to: 'agents#new', as: 'new_agent'
  post 'agents/create', to: 'agents#create', as: 'create_agent'

  get 'agents/show/:user_id', to: 'agents#show', as: 'show_agent'
  post 'agents/edit/:user_id', to: 'agents#edit', as: 'edit_agent'

  get 'agents/assign_client/:user_id', to: 'agents#assign_client', as: 'assign_client'
  post 'agents/create_assignation/', to: 'agents#create_assignation', as: 'create_assignation'

  match '/search_brokers', to: 'pages#search_brokers', as: 'search_brokers', via: [:get, :post]
  
  get 'clients/refer_broker/:user_id', to: 'clients#refer_broker', as: 'refer_broker'
  
  get 'clients/refer_agent/:user_id', to: 'clients#refer_agent', as: 'refer_agent'
  
  get 'clients/assign_broker/:user_id', to: 'clients#assign_broker', as: 'assign_broker'
  post 'clients/change_broker/:user_id', to: 'clients#change_broker', as: 'change_broker'


  post 'clients/create_referral/', to: 'clients#create_referral', as: 'create_referral'

  get 'clients', to: 'clients#index'
  get 'clients/new', to: 'clients#new', as: 'new_client'
  post 'clients/create_client', to: 'clients#create_client', as: 'create_client'

  get 'clients/show/:user_id', to: 'clients#show', as: 'show_client'
  post 'clients/update_client/:user_id', to: 'clients#update_client', as: 'update_client'

  get 'clients/edit/:user_id', to: 'clients#edit', as: 'edit_client'
  get 'update_agent/:id', to: 'agents#update', as: 'update_agents'
  
  get 'profile/view_profile/:id', to: 'profile#view_profile', as: 'view_profile'
  match 'profile/update_profile', to: 'profile#update_profile', as: 'update_profile', via: [:get, :post]


  devise_for :users
  get 'brokers_locations', to: 'pages#get_brokers_locations', as: 'brokers_locations'
  root 'pages#home'

  post 'get_states_by_country/:country_id', to: 'pages#get_states_by_country'

  post 'get_cities_by_country_and_state/:country/:state_id', to: 'pages#get_cities_by_country_and_state'

  get 'dashboard', to: 'dashboard#index', as: 'dashboard'
  
  get 'dashboard/show_user/:user_id', to: 'dashboard#show_user', as: 'show_user'

  post 'dashboard/edit_user/:user_id', to: 'dashboard#edit_user', as: 'edit_user'

  get 'transactions', to: 'transactions#index', as: 'transactions'

  get 'remove_user/:user_id', to: 'dashboard#remove_user', as: 'remove_user'

  match "clients/refer_client_from_broker", to: "clients#refer_client_from_broker", as: 'refer_client_from_broker', via: [:get, :post]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :user, class_name: "User", foreign_key: "user_id"    
  belongs_to :broker, class_name: "Broker", foreign_key: "broker_id"    
  has_many :transations, class_name: "Transaction"
  has_many :clients, class_name: "Client"

  def full_name
    "#{self.user.first_name} #{self.user.last_name}"     
  end
end

app/controllers/agents_controller.rb
class AgentsController < ApplicationController
  before_action :authenticate_user!
  before_action :validate_email_registered, only: [:create]
  before_action :get_clients, only: [:assign_client]
  before_action :has_valid_profile

  def index
    user = User.find(current_user.id)
    broker_id = user.broker.id if user.broker
    @agents = Agent.where(broker_id: broker_id)
  end

  def new
    @user = User.new
  end

  
  def show
    @user = User.find(params[:user_id])
  end

  def edit
    user_id = params[:user_id]
    agent = User.find(user_id)
    agent.first_name = params[:first_name] if params[:first_name]
    agent.last_name = params[:last_name] if params[:last_name]
    agent.phone = params[:phone] if params[:phone]
    agent.email = params[:email] if params[:email]
    agent.user_state = params[:user_state] if params[:user_state]    
    if agent.save!
      redirect_to agents_path, flash: {notice: "Agent successfully updated"}
    else
      render :edit
    end
  end

  def create
    @user = User.create(permit_params_user)
    if @user.save
      agent = Agent.new
      agent.user_id = @user.id
      agent.broker_id = User.find(current_user.id).broker.id
      
      respond_to do |format|
        if agent.save
           format.html { redirect_to agents_path, notice: 'Agent was successfully created.' }
           format.json { render :new, status: :created }
        else 
          flash[:error] = "error creating agent"
          format.html { render :new }
        end
     end
    else
      respond_to do |format|        
        format.html { render :new }
      end      
    end    
  end

  def assign_client
    @user = User.find(params[:user_id])
    @agent = Agent.find_by_user_id(@user.id)
  end
  
  def create_assignation
    agent = Agent.find(params[:agent_id])
    clients_ids = params[:agent][:client_id].reject(&:empty?)
    clients = Client.where(id: clients_ids)
    
    if clients
      clients.each do |client|
        agent.clients << client
      end
    end
    
    if agent.save!
      create_transaction(params)
      flash[:success] = "Assignation created succesfully"
      redirect_to agents_path
    else
      render :assign_client
    end
  end

  def create_transaction(params)

  end

  private
  

  def get_clients
    @clients = Client.all
  end

  def error_creating_user
    flash[:error] = "Error creating User, all fileds are required"
    redirect_to new_agent_path
  end

  def validate_email_registered
    unless params[:email].empty?
      user = User.find_by_email(params[:email])
      if user
        flash[:error] = "Error creating User, email is already registered"
        redirect_to new_agent_path
      end      
    end
  end

  def has_valid_profile
    valid = false    
    user = User.find(current_user.id)
    if current_user.role.downcase == 'broker'
      valid = user.broker      
    else
      valid = user.agent
    end    
    redirect_to profile_index_path, flash: {notice: "Please complete your profile"} unless valid
  end
  
  def permit_params_user
    params.permit(:first_name, :last_name, :email, :phone, :role, :password, :password_confirmation, :user_state)
  end

end

app/views/agents/assign_client.html.erb
<div class="container update-client">
  <%= form_with(url: create_assignation_path(@user), method: "post") do |f| %>
  <h2>Assign Client</h2>

  <%= f.hidden_field :agent_id, value: @agent.id %>

  <div class="form-outline mb-4">
    <%= f.label :first_name, class: "form-label" %><br />
    <%= f.text_field :first_name, autofocus: true, autocomplete: "First name", value: @agent.user.first_name, readonly: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :last_name, class: "form-label" %><br />
    <%= f.text_field :last_name, autofocus: true, autocomplete: "Last name", value: @agent.user.last_name, readonly: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :phone, class: "form-label" %><br />
    <%= f.text_field :phone, autofocus: true, autocomplete: "Phone", value: @agent.user.phone, readonly: true, class: "form-control" %>
  </div>

  <div class="form-outline mb-4">
    <%= f.label :email, class: "form-label" %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", value: @agent.user.email, readonly: true, class: "form-control" %>
  </div>
  
  <div class="field">
    <%= f.label "Assign client", class: "form-label" %>
    <%= collection_select(:agent, :client_id, @clients, :id, :full_name, {}, {:multiple => true, class: "form-control"}) %>
  </div>
  <br/>


  <br/>
  
  <div class="actions d-grid col-12 mx-auto">
    <%= f.submit "Assign", class: "btn btn-success" %>
  </div>
  <% end %>
</div>

app/views/agents/index.html.erb
<div class="agents-container">  
  <h2>Agents list</h2>
  <div class="list">
  <div class="actions d-grid col-10 justify-content-md-start">
    <%= link_to "New Agent", new_agent_path, class: "btn btn-primary mb-4" %>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">name</th>
        <th scope="col">email</th>
        <th scope="col">phone</th>
        <th scope="col">User status</th>
        <th scope="col"># clients</th>        
      </tr>
    </thead>
    <tbody>
    <% count = 0 %>
    <% @agents.each do |agent| %>
      <tr>
        <td><%= count += 1 %></td>        
        <td><%= link_to agent.full_name, show_agent_path(agent.user.id)  %></td>
        <td><%= agent.user.email %></td>
        <td><%= agent.user.phone %></td>
        <td><%= agent.user.user_state %></td>
        <td><%= agent.clients.count %></td>        
      </tr>
    <% end %>
    </tbody>
  </table>
  </div>
</div>

app/views/agents/new.html.erb
<div class="container new-client">
    <% if @user.errors.any? %>
      <div id="errorExplanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  <%= form_with(url: create_agent_path(@user), local: true, method: "post") do |f| %>
    <h2>Create new Agent</h2>
    <%= f.hidden_field :user_state, value: 'active' %>
    <div class="form-outline mb-4">
      <%= f.label :first_name, class: "form-label" %><br />
      <%= f.text_field :first_name, autofocus: true, autocomplete: "First name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :last_name, class: "form-label" %><br />
      <%= f.text_field :last_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :phone, class: "form-label" %><br />
      <%= f.number_field :phone, autofocus: true, autocomplete: "Phone", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :email, class: "form-label" %><br />
      <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>
    
    <%= f.hidden_field :role, value: "agent", class: "form-control" %>
    
    <div class="field">
      <%= f.label "password (6 characters minimum)", class: "form-label" %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
    </div>

    <div class="field">
      <%= f.label :password_confirmation, class: "form-label" %><br />
      <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
    </div>
    
    <div class="actions d-grid col-12 mx-auto">
        <%= f.submit "Create agent",  class: "btn btn-success btn-block mb-4" %>
    </div>    
  <% end %>
</div>

app/views/agents/show.html.erb
<div class="container update-client">

  <% if @user.errors.any? %>
      <div id="errorExplanation">
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>

  <%= form_with(url: edit_agent_path(@user), local: true, method: "post", action: :edit) do |f| %>
    <h2>Update Agent</h2>

    <%= f.hidden_field :user_id, value: @user.id %>
    
    <div class="form-outline mb-4">
      <%= f.label :first_name, class: "form-label" %><br />
      <%= f.text_field :first_name, value: @user.first_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :last_name, class: "form-label" %><br />
      <%= f.text_field :last_name, value: @user.last_name, autofocus: true, autocomplete: "Last name", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :phone, class: "form-label" %><br />
      <%= f.number_field :phone, value: @user.phone, autofocus: true, autocomplete: "Phone", class: "form-control" %>
    </div>

    <div class="form-outline mb-4">
      <%= f.label :email, class: "form-label" %><br />
      <%= f.email_field :email, value: @user.email, autofocus: true, autocomplete: "email", class: "form-control" %>
    </div>

    <br/>

    <div class="row g-3">
      <div class="col-md-2">
        <%= f.label "User state:", class: "form-label" %><br />
      </div>
      <div class="col-md-2">        
        <%= radio_button_tag :user_state, "inactive", @user.user_state.downcase == 'inactive' %>
        <%= f.label "Inactive", class: "form-label" %><br />
      </div>
      
      <div class="col-md-4">
        <%= radio_button_tag :user_state, "active", @user.user_state.downcase == 'active' %>
        <%= f.label "Active", class: "form-label" %><br />
      </div>
    </div>
    
    <br/>
    
    <div class="actions d-grid col-12 mx-auto">
      <%= f.submit "Update", class: "btn btn-success" %>
    </div>
  <% end %>
</div>